### ISSUE TITLE
Develop Teacher Archetypes

### ISSUE THREAD

**Issue by JoJoBahnam** [bootstrapworld/data-management#5]
Some teachers only implement a few lessons over a few weeks, some use the entire curriculum. Some teach in math courses, some in social studies. We should develop our own segmentation and archetypes, and determine how we treat these differently.

**Comment by er1c456** [comment]
We can reopen or create a new issue when we're ready to look closely at teacher archetypes. I think this will be a good activity in the Fall after we can process our summer training data.
